### ISSUE TITLE
How can I update assignment files easily...

### ISSUE THREAD

**Issue by BioMiM** [snu-sf-class/pl201602#12]
I found a mk.py in 'skeleton' folder and I tried to run mk.py with python. but that makes some errors...

I want to update only assignments/02 folder but now i'm downloading all things with clicking 'clone or downloads' button in Github...

I'm just started learning programmings.. so i do not know what skeleton or some other files do.

how can i download only new things?

**Comment by jeehoonkang** [comment]
Dear @BioMiM ,
- `skeleton` directory is not intended to be directly used by students.  Please just ignore it.
- I assume you cloned this repository, right?  Then you  can just `git pull` to download the new contents.
- If not, just please download the whole repository again..

**Comment by BioMiM** [comment]
Thanks! now I can update it with terminal.
