### ISSUE TITLE
Submission link ID and PW

### ISSUE THREAD

**Issue by nicholasDYtan** [snu-sf-class/pl201602#16]
What is the login and password for the submission link, do I need to register or something?
For reference, my SNU ID is 2016-81812.

**Comment by aqjune** [comment]
You don't have to register. To login, follow https://github.com/snu-sf-class/pl201602 .

**Comment by nicholasDYtan** [comment]
As in, when I click the link for submission, it asks me to log in before I can upload my solution. What do I ise as the ID and PW for the login?

**Comment by han-minhee** [comment]
From the README.md :
2016/09/09: The evaluation server is open.(http://147.46.219.145:8100/ ) Your ID/Password is Student Number. Please change your password.
:)

**Comment by nicholasDYtan** [comment]
alright, thank you!
