### ISSUE TITLE
username/password not working.

### ISSUE THREAD

**Issue by ghost** [snu-sf-class/pl201602#18]
I typed my student number in two formats - 201111287/2011-11287.

But it didn't work.

Do I type wrong??

**Comment by dreamtaker1001** [comment]
both id and pw need -(dash).
like this 2011-11287/2011-11287

**Comment by ghost** [comment]
Thank you :) I got password from TA. Whoever has problem with login, you'd better send email to TA and he will help.

Thanks :)
