### ISSUE TITLE
opam init 문제

### ISSUE THREAD

**Issue by culpare** [snu-sf-class/pl201602#19]
다 늦게 질문 드려서 죄송합니다

다름이 아니라 설치가 안되네요...

쉽다길래 지금부터 하려고 했었는데
opam init --comp 4.03.0

여기서부터 안됩니다 

Debian-like Linux이고 ubuntu 14.04 desktop 64비트를 사용하는 가상머신입니다 

제가 성공한 부분은 
1. sudo apt-get install liblablgtksourceview2-ocaml-dev
2. sudo apt-get install opam  
   까지고요 

init서부터 안 되는 바람에 한 시간 동안 여러 가지 방법을 시도해봤습니다 

먼저 에러 메시지에 버젼이 1.1.1이라서 안된다는 말이 있길래 버젼업을 해보려고 apt-get update라거나 opam upgrade를 시도해봤으나 전자는 소용없었고 후자는 init이 안되서 불가능합니다

다음으로 http://m.blog.naver.com/carrotcarrot/40208526763 이 블로그에 있는 것처럼 다시 설치 해봤는데 소용없었고요...

마지막으로 opam init failed, opam init error 키워드로 구글링해서 찾아낸 https://github.com/ocaml/opam/issues/481(그런데 이건 remove로 어떻게 지운다는 건지 모르겠습니다. opam 찾아봐도 없더군요.), https://github.com/ocaml/opam/issues/1955를 봐도 해결이 되지 않았습니다 

도저히 방법이 없어서 질문드립니다
자세한 에러 메시지는 다음과 같습니다
![2](https://cloud.githubusercontent.com/assets/14194366/19029606/b3af73e4-8982-11e6-88ca-6eed38eef53f.JPG)
![default](https://cloud.githubusercontent.com/assets/14194366/19029608/b7024bf2-8982-11e6-9fc3-198fee0a3595.JPG)

**Comment by jeehoonkang** [comment]
- as said in the readme, please use block quotation for codes.  Please do not upload an image of it.
- The error is not familiar to me, but I guess it's due to the lack of resources in the virtual machine.  What's your VM's spec?
- Did you follow the instruction in http://opam.ocaml.org/doc/Install.html ?  Find `Ubuntu` in the documentation.

**Comment by culpare** [comment]
가상머신 스팩은 dual-core, 50GB, 2GB 렘입니다 

예, 물론 그거 따라서 해봤습니다 

안 되더군요... 

위에 sudo apt-get install opam 말고도 아래의 비정규 스토리지로 해봤는데도 안 되고 ubuntu 부분에 있는 그 설명이 네이버 블로그에 있던 그거더라고요 

그리고 코드에 관해서는 다음부터는 그렇게 하겠습니다

**Comment by jeehoonkang** [comment]
Did you do it?

```
add-apt-repository ppa:avsm/ppa
apt-get update
apt-get install ocaml ocaml-native-compilers camlp4-extra opam
```

`sudo apt-get install opam` is doomed, it seems.  `apt-get remove opam` and try again.  If it is also unsuccessful, try recreating a new VM and install again.

**Comment by culpare** [comment]
다 했는데 ㅠㅠ

알겠습니다 다시 깔고 해보죠 
어쩌면 우분투 버젼이 문제일 수도 있으니까요 
새롭게 받아서 다 지우고 다시 해보겠습니다

**Comment by culpare** [comment]
해결했습니다
지우고 다른 버젼을 받았고요 
지금 문제를 넘은 후에 문제가 하나 더 발생했었는데 의존성 문제였고 그냥 그걸 따로 설치해서 해결했습니다 감사합니다 

왜 안된건지 이유는 저도 모르겠네요...
