### ISSUE TITLE
coqide install error (opam)

### ISSUE THREAD

**Issue by ghost** [snu-sf-class/pl201602#2]
I got this error while installing ide.
I downloaded all relevant files and adjusted PATH, but same problem occurs.

Thanks

```
----------------------------------------------------------------------------------------

The following actions will be performed:
  ∗  install conf-gtksourceview 2             [required by coqide]
  ∗  install lablgtk            2.18.5        [required by coqide]
  ∗  install coqide             8.5.2
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[coqide] Archive in cache
[lablgtk] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of
        conf-gtksourceview failed at
        "pkg-config
        gtksourceview-2.0".

#=== ERROR while installing conf-gtksourceview.2 ==============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config gtksourceview-2.0
# path         /Users/woong/.opam/system/build/conf-gtksourceview.2
# compiler     system (4.02.3)
# exit-code    1
# env-file     /Users/woong/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-996-ffb3fd.env
# stdout-file  /Users/woong/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-996-ffb3fd.out
# stderr-file  /Users/woong/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-996-ffb3fd.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install coqide  8.5.2
  ∗  install lablgtk 2.18.5
The following actions failed
  ∗  install conf-gtksourceview 2
No changes have been performed

=-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtksourceview
   2.0 development packages installed
   on your system
=> On OSX, install the `gtksourceview'
   and `libxml2' packages and define
   PKG_CONFIG_PATH:
```

**Comment by jeehoonkang** [comment]
Thank you for reporting it!
- Please use block quotations for codes.
- As the error message says, it seems  you need to install `gtksourceview` and `libxml2` libraries.  After installing them Coq will be installed, I guess.
- In case you don't want to do that, install Coq with binaries.  I updated the README (https://github.com/snu-sf-class/pl201602#coq).

**Comment by ghost** [comment]
Thanks! I already installed those libraries.

But I will try again or install binaries as you said

Thanks

Gi-Woong Lee

2016년 9월 7일 수요일, Jeehoon Kangnotifications@github.com님이 작성한 메시지:

**Comment by jeehoonkang** [comment]
In my OS X machine, after `brew install gtksourceview libxml2`, `opam install coqide.8.5.2` worked.  May I ask how did you install those libraries?

**Comment by ghost** [comment]
Hello, Jeehoon.

I could not use computer because I came hometown today. I will check it
tomorrow, is it okay? :)

Thanks.

Best regards, Gi-Woong Lee

2016-09-09 12:40 GMT+09:00 Jeehoon Kang notifications@github.com:

**Comment by jeehoonkang** [comment]
Sure!

**Comment by ghost** [comment]
Hi jeehoon. Thanks for helping me.

I installed coqide. It was error while installing gtksourceview, because it required 'brew install libpng' and I need to do some extra stuffs to install it.

Thanks for helping me.
