### ISSUE TITLE
proof 안에 proof

### ISSUE THREAD

**Issue by ghost** [snu-sf-class/pl201602#27]
문제를 풀다가 proof 안에 Lemma를 써서 증명했는데
아래와 같은 메세지가 뜨는데요.
문제 푸는데에는 지장이 없는 건가요??

Nested proofs are deprecated and will
stop working in the next Coq version

**Comment by aqjune** [comment]
채점 서버에 점수가 뜨기만 하면 괜찮습니다.
일단 채점서버에 간단한 증명으로 테스트 해보니 문제는 없는 것 같습니다만, 혹시 모르니 choigyumin님도 한 번 채점을 시도해보세요.

**Comment by ghost** [comment]
아, 감사합니다!
일단 이번 과제는 이렇게 제출하겠습니다.

그런데 혹시 나중에 시험문제에서 불이익이 있을까 궁금합니다…..

Gyumin Choi 최규민
Seoul National University - Statistics, CS
+82 10 5195 2047 / choigyumin@gmail.com

**Comment by jeehoonkang** [comment]
There will not be a penalty for triggering the warning.

**Comment by ghost** [comment]
감사합니다

Gyumin Choi 최규민
Seoul National University - Statistics, CS
+82 10 5195 2047 / choigyumin@gmail.com
