### ISSUE TITLE
Assignment 04 Errors

### ISSUE THREAD

**Issue by hoonga** [snu-sf-class/pl201602#28]
Both in server and skeleton
E05_1 starts with

`require exports P01`

which needs to be changed to

`require exports P05`

similar problem also exists through out E06_1 ~ E09_1

**Comment by minsuu** [comment]
I get same error here!

**Comment by isutare412** [comment]
also here.

**Comment by aqjune** [comment]
Sorry for inconvenience. I updated the skeleton.
