### ISSUE TITLE
[Assignment 4] P04.v unable to load 'c_plus'

### ISSUE THREAD

**Issue by minsuu** [snu-sf-class/pl201602#30]
`P04.v` needs `c_plus` function to prove some theorem in it, however, without rewriting the definition of `c_plus` from `P03.v`, you'll probably get the compile error like this:

```
STDERR:
File "./P04.v", line 23, characters 2-13:
Error: Unable to unify "c_plus c_three c_three" with "c_mult c_two c_three".
make[1]: *** [P04.vo] Error 1
make: *** [P04.vo] Error 2
```

I just copied and pasted its definition, and it worked well.

**Comment by hoonga** [comment]
probably the
`require export` statement is wrong.

**Comment by iskim517** [comment]
I got the same issue, and your solution worked. I still don't know why this happens. What's the meaning of "require export is wrong"?

**Comment by minsuu** [comment]
@iskim517 I think the issue #11 is related to this.

**Comment by aqjune** [comment]
Sorry for inconvenience. Yes, the `c_plus` of your implementation must be copied into P04.v. This info must have been mentioned as a comment in P04.v . I'll update the P04.v in skeleton.
The reason why Coq fails to do reflexivity is that submission server uses the definition of `c_plus` in skeleton P03.v . Submission server compiles your P04.v with skeleton P01.v/P02.v/P03.v .
