### ISSUE TITLE
4번 과제에 대해 질문드립니다.

### ISSUE THREAD

**Issue by makesource** [snu-sf-class/pl201602#31]
4번 과제중, Definition으로 짜여진 skeleton code를
Fixpoint로 변경해도 되는지 궁금합니다.

**Comment by makesource** [comment]
Definition 으로 해결하였습니다.
하지만 만약 시험이나 다른 과제에 대해서 이런 경우가 있다면, Fixpoint로 함수를 작성하여도 감점요인이 되는지 궁금합니다.

**Comment by aqjune** [comment]
안녕하세요, 답변이 늦어서 죄송합니다.

감점요인이 되지 않습니다.
