### ISSUE TITLE
assignment 4, P05 질문드립니다.

### ISSUE THREAD

**Issue by BioMiM** [snu-sf-class/pl201602#32]
(*\* Hint: you can use [apply] with previously defined lemmas, not
    just hypotheses in the context.  Remember that [SearchAbout] is
    your friend. *)

위의 SearchAbout에 대한 힌트참조하여서

Search rev.
Search (_++_).
Search (_::_).
등등.. 다른 여러가지로 검색을 시도하였는데 마땅한것이 검색되지 않았습니다. D.v안의 것들만 검색이 되고, 검색이 되지않는것에 대해 apply는 사용이 불가한 것 같습니다.

그래서 힌트를 무시하고 apply rev_involutive.를 하기위해서 이전에 숙제하였던 것들을 참조하여 rev_involutive,  rev_snoc, rev, snoc, 등등을 모두 긁어왔으나 natlist를 list nat으로 바꾸어 주어야 한다던가, 이전 숙제에서는 Require Export ~가 되어있는덕에 simpl.을 했을 때 다르게 결과가 나온다던가.. 하는 일들이 계속되어서, Lemma를 이용해서 증명을 하는 것에는 너무나 많은 Lemma, Fixpoint 들이 필요할것 같다는 생각이 들어서 포기하였습니다. 숙제를 혼자힘으로 하라고 하셔서 이 한 문제에 대해서 꽤 오랜시간동안 고민을 했습니다만, 도저히 혼자힘으로 해결하기가 힘들것같아서 질문드립니다.

D.v나 P05.v 에 Require Export List 따위의 것들을 추가하여도 되는지 궁금하고,
힌트대로 apply를 이용해서 푸는 것인지. 아니면 새로운 lemma들을 계속해서 만들어서 풀어야하는지 궁금합니다.

**Comment by jeehoonkang** [comment]
- Require Import를 새로 하시면 안됩니다.
- 새로운 lemma들을 계속해서 만들어서 푸실 수 있으리라 생각합니다.

**Comment by aqjune** [comment]
저도 예전에 PL수업을 들을 때 한 문제를 풀기 위해 여러 lemma를 정의하고 했던 기억이 있긴 해요.

자기가 빨리 증명할 수 있을 것 같으면서 문제에 필요한 lemma들을 잘 생각해내는 능력이 필요했던 것 같습니다.

**Comment by BioMiM** [comment]
답변 감사합니다.
hint는 무시해야겠군요...
