### ISSUE TITLE
Assignement 06

### ISSUE THREAD

**Issue by sebspas** [snu-sf-class/pl201602#40]
There is an error in E03_1.v, the name of the function in the check is not the right one....

**Comment by aqjune** [comment]
I updated the file.

**Comment by sebspas** [comment]
i'm sorry but it's still giving me an error : 
File "./E03_01.v", line 5, characters 21-22:
Syntax error: '.' or '...' expected after [tactic:tactic](in [proof_mode:subgoal_command]).
make[1]: **\* [E03_01.vo] Error 1
make: **\* [E03_01.vo] Error 2

**Comment by iskim517** [comment]
In the github repository it was updated, but in the evaluation server it's still not fixed.

**Comment by aqjune** [comment]
I updated the file in server. Sorry for inconvenience. I checked that the server checks well.

**Comment by iskim517** [comment]
Now it works well. Thank you.
