### ISSUE TITLE
Assignment 06 submission error

### ISSUE THREAD

**Issue by soochan-lee** [snu-sf-class/pl201602#43]
When I submit my assignment, the status changes to FORBIDDEN.
Is there any problem on the server?
Please check.

**Comment by aqjune** [comment]
What is your student id?

**Comment by soochan-lee** [comment]
It's 2013-11544.

**Comment by aqjune** [comment]
Hello. Your P08.v contains 'Admitted', which is not allowed in our assignment.
You can check whether your assignments forbidden tactic by running `check.sh`.

**Comment by aqjune** [comment]
By the way, during the check I had to change password so I can log in. Sorry for inconvenience.
Email us (pl201602@sf.snu.ac.kr ) , then I'll respond you with your new password.
