### ISSUE TITLE
bool vs Datatypes.bool?

### ISSUE THREAD

**Issue by hoonga** [snu-sf-class/pl201602#45]
When using reflect beq_nat returns bool when Datatypes.bool is expected.

Is there a way to fix this?

**Comment by sangmoon** [comment]
저도 같은 문제가 나오는데 해결책이 있나요 ㅠㅠ??

**Comment by aqjune** [comment]
안녕하세요, 늦게 확인해서 죄송합니다. 오늘 중에 답변 드리도록 하겠습니다.

**Comment by aqjune** [comment]
답변이 늦어서 정말 죄송합니다.
1번 문제 혹은 2번 문제를 풀다가 해당 에러가 나온 것인가요?
혹시 어떤 상황에서 에러를 만났는지 알 수 있을까요?
감사합니다.
