### ISSUE TITLE
"aexp" against "Imp.aexp" Ex06 Ass 07

### ISSUE THREAD

**Issue by sebspas** [snu-sf-class/pl201602#46]
The term "e1" has type "aexp" while it is expected to have type "Imp.aexp".

Any way to fix this ?

**Comment by sebspas** [comment]
`Fixpoint s_compile (e : aexp) : list sinstr 
  match e with
  | ANum n => [SPush n]
  | AId id => [SLoad id]
  | APlus e1 e2 => (s_compile e1) ++ (s_compile e2) ++ [SPlus]`

Error: In environment
e : aexp
e1 : aexp
e2 : aexp
The term "e1" has type "aexp" while it is expected to have type "Imp.aexp".

I dont understand this error ....

**Comment by aqjune** [comment]
Hello. While solving the problem I didn't see the error. Could you give me more detail?
Thanks
