### ISSUE TITLE
E06_01.v: Error due to missing Import clause

### ISSUE THREAD

**Issue by iskim517** [snu-sf-class/pl201602#47]
E06_01.v does not import ListNotations, so it just refuses being evaluated.

Please fix it by adding "Import ListNotations."

**Comment by iskim517** [comment]
There are same issues in E06_02.v, E06_03.v.

**Comment by iskim517** [comment]
I found a workaround. Changing "Import ListNotations." to "Export ListNotations." in P06.v should solve this problem.

**Comment by aqjune** [comment]
I updated E06_0n.v files. Thank you.

**Comment by iskim517** [comment]
Confirmed. Thank you. Closing.
