### ISSUE TITLE
forbidden.txt still contains some "ALLOWED" tactics

### ISSUE THREAD

**Issue by iskim517** [snu-sf-class/pl201602#48]
D.v says:

   - You are ALLOWED to use any tactics including:
     [tauto], [intuition], [firstorder], [omega].

But actually we are forbidden to use them, because "forbidden.txt" still contains them.
Please fix it. Thank you

**Comment by aqjune** [comment]
I updated the forbidden.txt.
Sorry for not allowing them.
Thanks

**Comment by iskim517** [comment]
It works well now. Thank you. Closing.
