### ISSUE TITLE
Evaluation Server Accepts "Axiom"

### ISSUE THREAD

**Issue by iskim517** [snu-sf-class/pl201602#49]
I tried submitting Problem 14 with following and it passed test, which should be considered FORBIDDEN.

Axiom subst_equiv: forall i1 i2 a1 a2,
  var_not_used_in_aexp i1 (subst_aexp i1 a1 a2) ->
  cequiv (i1 ::= a1;; i2 ::= a2)
         (i1 ::= a1;; i2 ::= subst_aexp i1 a1 a2).

It can be resolved with adding "Axiom" to the forbidden.txt file.

My student ID is 2010-11736, and that submission was at Nov. 26, 2016, 11:10 a.m. I will try to solve this with different and correct way, but I think this should be fixed.

**Comment by aqjune** [comment]
Thank you. I updated forbidden.txt.

**Comment by iskim517** [comment]
Closing.
