### ISSUE TITLE
Proving 'hoare_if_weakest' and 'hoare_seq_weakest' in Ass09 is too hard

### ISSUE THREAD

**Issue by minsuu** [snu-sf-class/pl201602#58]
I've spent so many hours in solving `hoare_if_weakest` and `hoare_seq_weakest`...ended up with frustration..

Proving `is_wp` consists of two parts, and the hard one is the second one, where we should use `{{P'}} c {{Q}}` to get `P' ->> P`.

These two theorems are quite different from `hoare_asgn_weakest`, which enables to derive the exact state change after the command. (ex. `(Q [X |-> a]) st` simplifies to `Q (t_update st X (aeval st a))`)

However, since `seq` and `if` command include arbitrary commands, we don't have any knowledge about the state change. (Can't assure even the state exists!) That makes we cannot use the variable `st'`, which blocks the utilization of `is_wp` in the hypothesis..

Is there any way to solve this problem? Some hints may help me a lot!

**Comment by makesource** [comment]
help me...

**Comment by Jooh34** [comment]
ㅠㅠㅠ too hard

**Comment by soochan-lee** [comment]
I think they require 'excluded middle' as axiom.
Is it possible to prove without it?

**Comment by iskim517** [comment]
In P05.v, (beval st b) is always one of true or false. So actually you don't need excluded_middle axiom.

**Comment by minsuu** [comment]
WOW.. thanks to @iskim517, `hoare_if_weakest` is solved by destructing `{{P'}} IFB b THEN c1 ELSE c2 FI {{Q}}` into 2 cases(with `beval st b=true` and `beval st b=false`), proved by lemma..

**Comment by minsuu** [comment]
`eauto` solved `hoare_seq_weakest` easily...  I'll close this issue!
