### ISSUE TITLE
[Cygwin] environment path(?) seems wiered...

### ISSUE THREAD

**Issue by Holim0711** [snu-sf-class/pl201602#8]
When I try to make clean, it fails like this.

$ make -f Makefile.coq clean
rm -f blah blah...
find . -name .coq-native -type d -empty -delete
FIND: ▒Ű▒ ▒▒▒▒ ▒▒▒▒▒▒ Ʋ▒▒▒ϴ▒.
make: **\* [clean] Error 2

'FIND: ▒Ű▒ ▒▒▒▒ ▒▒▒▒▒▒ Ʋ▒▒▒ϴ▒.' <- This seems like Windows 'find.exe' error message.
But when I try 'which find' in Cygwin, then the result is okay, '/usr/bin/find'.

**Comment by jeehoonkang** [comment]
Did you try `find ...` (the command make tries to do)?

**Comment by Holim0711** [comment]
Yes, I tried in command line. And it works good. But only when trying with 'make', it fails...

**Comment by Holim0711** [comment]
http://stackoverflow.com/questions/3297953/cygwin-make-cant-find-cygwin-commands
This is a similar problem from StackOverflow, but the solution didn't work for me..

**Comment by Holim0711** [comment]
I made the new value $(FIND) at the top of 'Makefile.coq' and change the 'find' command.
($(FIND) is '/usr/bin/find.exe')

But then this error came...
process_begin: CreateProcess(NULL, /usr/bin/find.exe . -name .coq-native -type d -empty -delete, ...) failed.
make (e=2): ▒▒▒▒▒▒ ▒▒▒▒▒▒ ã▒▒ ▒▒ ▒▒▒▒▒ϴ▒.

**Comment by jeehoonkang** [comment]
I don't think I can reproduce the symptom.  Would you please come to my office next Monday or Tuesday?  Please mail to pl201602@sf.snu.ac.kr to make an appointment.

Thank you,
Jeehoon

**Comment by aqjune** [comment]
For the `CreateProcess(NULL, ...` error, I found the error message in https://github.com/libusb/libusb/issues/21.
It says that if there exists another `make.exe` in your computer, then it will cause error.
Did you install MinGW in your computer & PATH has the mingw path? You can rename `make.exe` files in your mingw folder and retry it.
One more thing.. Cygwin has two versions : 32-bit / 64 bit. You can check whether you installed correct cygwin as well.

**Comment by Holim0711** [comment]
Oh, the path of 'make' is from Coq, not Cygwin. That would be the clue.
I will give it a try.

**Comment by Holim0711** [comment]
It is solved!
I didn't install the 'make' package...
There is 'make' in Coq, so I didn't know that I didn't.
Check whether you install right packages. 'make' package and also 'zip' package too.
